# This configuration file contains 'fingerprints' of SD card structures for various cameras
# format:
#
# [cameras.Camera_name]
# structure = ["DCIM", "MISC"]  # - list of paths to directories that must be present on the SD card (ralative to SD-root)
#
# [cameras.Camera_name2]
# structure = ["PRIVATE/AVCHD/BDMV/CLIPINF", "PRIVATE/AVCHD/BDMV/PLAYLIST"] # - requirement for the presence of a chain of nested directories

[cameras]

[cameras.Sony_A73]
structure = ["DCIM", "PRIVATE/M4ROOT/CLIP", "PRIVATE/M4ROOT/GENERAL", "PRIVATE/SONY"]

[cameras.Canon_EOS]
structure = ["DCIM", "CANONMSC"]

[cameras.Canon_PowerShot_G7X]
structure = ["DCIM", "MISC", "CANONMSC", "PRIVATE"]

[cameras.Sony_Alpha_6000]
structure = ["DCIM", "MISC", "PRIVATE/SONY"]

[cameras.Android_Device]
structure = ["DCIM/Camera", "Pictures/Screenshots", "Download"]

[cameras.DCIF_compatible]
structure = ["DCIM"]
