[cameras]
[cameras.Sony_A73]
structure = ["DCIM", "AVF_INFO", "PRIVATE/AVCHD/BDMV/CLIPINF", "PRIVATE/AVCHD/BDMV/PLAYLIST", "PRIVATE/AVCHD/BDMV/STREAM", "M4ROOT/CLIP", "M4ROOT/GENERAL", "M4ROOT/SUB", "M4ROOT/THMBNL", "M4ROOT/SONY"]

[cameras.Canon_EOS_5D]
structure = ["DCIM", "MISC"]
